[workspace]
resolver = "2"
members = [
    "ggoled_cli",
    "ggoled_lib",
    "ggoled_draw",
    "ggoled_app", # Windows-only
]
default-members = [
    "ggoled_cli",
    "ggoled_lib",
    "ggoled_draw",
]

[profile.release]
strip = true
lto = true